config/routes.rb
Rails.application.routes.draw do
  get 'student/new'
 post "students/:id"         => "students#show"

  root 'static_pages#home'
  get  '/signup',  to: 'students#new'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	before_save { self.email = email.downcase }

	validates :name, presence:{:message=>"cant blank"}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    validates :gender, presence: true
	validates :passward, presence: true, length: { minimum: 6 }
	validates :address, presence: true
	validates :country, presence: true
	validates :passward, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  	def index
    	@students = Student.all
  	end
	def new
	    @student = Student.new
	end
	def show
		@student = Student.find(params[:id])
    end
	def create
	    @student = Student.new(student_params)    # Not the final implementation!
		  if @student.save
	      		@students = Student.all
	      		render 'index'
	      else
	      render 'new'
	      end
  	end

	
  	def edit
	    @student = Student.find(params[:id])
  	end
  	def update
	    @student = Student.find(params[:id])
	    if @student.update_attributes(student_params)
	      flash[:success] = "Profile updated"
	      @students = Student.all
	      render 'index'
	    else
	      render 'edit'
	    end
	end
	def destroy
    	@student = Student.find(params[:id]).destroy
    	flash[:success] = "student deleted"
    	redirect_to @student
  	end

  	private

    def student_params
      params.require(:student).permit(:name, :email,
                                   :gender, :address, :country, :passward)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Student Crud Operation", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Student Registration</h1>
  <%= link_to "Student List", students_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/students/edit.html.erb
<% provide(:title, "Edit student") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
       <% if @student.errors.any? %> 
            <h2>Errors : </h2>
            <ul>  
                <% @student.errors.full_messages.each do|message| %>
                   <li><%= message %></li>
                <% end %>
            </ul>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :gender %>
      <%= f.radio_button :gender, 'Male' %> Male
      <%= f.radio_button :gender, 'female' %> female</br>

       <%= f.label :address %>
      <%= f.text_area :address %>

      <%= f.label :Country %>
      <%= f.select :country, [['India','India'],['Pakistan','Pakistan'],['Canada','Canada']] %>

      <%= f.label :passward %>
      <%= f.password_field :passward %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

   
  </div>
</div>

app/views/students/index.html.erb
<% provide(:title, 'All students') %>
<h1>All students</h1>
<%= link_to "New Form","/students/new" %>
<ul class="users">
   <table class="table table-bordered">
	    <thead>
	      <tr>
	        <th>Firstname</th>
	        <th>Email</th>
	        <th>gender</th>
	        <th>address</th>
	        <th>Country</th>
	        <th>Action</th>

	      </tr>
	    </thead>
  		<% @students.each do |student| %>
		    <tbody>
		      <tr>
		        <td><%= student.name %></td>
		        <td><%= student.email %></td>
		        <td><%= student.gender %></td>
		        <td><%= student.address %></td>
		        <td><%= student.country %></td>
		        <td><%= link_to "Edit", edit_student_path(student) %></td>
		        <td><%= link_to "Show", student, method: :show%></td>
		        <td><%= button_to 'Remove', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    </tbody>
  		<% end %>
  </table>
</ul>

app/views/students/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Student Registration</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  
     <%= form_for (@student) do |f| %>
    <%= link_to "Students", students_path %>
     <% if @student.errors.any? %> 
            <h2>Errors : </h2>
            <ul>  
                <% @student.errors.full_messages.each do|message| %>
                   <li><%= message %></li>
                <% end %>
            </ul>
      <% end %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :gender %>
      <%= f.radio_button :gender, 'Male' %> Male
      <%= f.radio_button :gender, 'female' %> female</br>

       <%= f.label :address %>
      <%= f.text_area :address %>

      <%= f.label :Country %>
      <%= f.select :country, [['India','India'],['Pakistan','Pakistan'],['Canada','Canada']] %>

      <%= f.label :passward %>
      <%= f.password_field :passward %>
  

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<% provide(:title, @student.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="student_info">

      	<%= form_for Student.new do |f| %>
  <%= link_to "Students", students_path %></br>
    
      	  <%= f.label :NAME  %>
	        <%= @student.name %></br>
	      <%= f.label :EMAIL  %>
      		<%= @student.email %></br>
	      <%= f.label :GENDER  %>
		    <%= @student.gender %></br>
	      <%= f.label :ADDRESS  %>
		    <%= @student.address %></br>
	      <%= f.label :COUNTRY  %>
		    <%= @student.country %></br>
		<% end %>
    </section>
  </aside>
</div>